language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
os:
  - linux
  - osx
#  - windows
sudo: false
install:
  - g++ --version
  - npm --version
  - npm install
  - wc -l src/parser.c
  - wc -c build/Release/*.node
script:
  - npm test
