version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
        name: install
        command: npm i
      - run:
        name: test
        command: npm test
